# Generated by Django 4.0.1 on 2022-01-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cloth', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
