# Generated by Django 4.0.1 on 2022-01-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('synonyms', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
                ('image_text', models.CharField(max_length=20)),
            ],
        ),
    ]
